# Generated by Django 5.0 on 2024-06-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_solicitacaoexame_pedidoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoexame',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
