# Generated by Django 5.0 on 2024-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_solicitacaoexame_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoexame',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
